print("=====AutoTest Start======")
print('~~~~~~~~~测试用例1~~~~~~~~~')
print('请输入测试用例1的手机号：')
tel1 = input('tel1 = ')
print(type(tel1))
# print('【弹窗窗口已弹出，进行自动化填单测试！】')
# print('aaaaaa')
# print('~~~~~~~~~测试用例2~~~~~~~~~')
# print('【弹窗窗口已弹出，进行自动化填单测试！】')
# print('bbbbbb')
# print('~~~~~~~~~测试用例3~~~~~~~~~')
# print('【弹窗窗口已弹出，进行自动化填单测试！】')
# print('cccccc')
# print("=====AutoTest Over======")